spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: algo-trading-platform
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: postgres
  cache:
    caffeine:
      spec: maximumSize=5000
    cache-names:
      - historicCandles
      - accountId
      - instruments
  jackson:
    deserialization:
      use-big-decimal-for-floats: true

invest:
  connector:
    token: ${BROKER_TOKEN}
    app-name: ${spring.application.name}

application:
  backtesting:
    tempFileDirectory: ${TEMP_FILE_DIRECTORY}
  trading:
    default-commission: 0.0004
    available-delayed-candles-count: 3
    place-order-retry-count: 3
    class-code: "TQBR"
    trading-schedule:
      - from: "07:00:00"
        to: "09:50:00"
      - from: "10:00:00"
        to: "18:40:00"
      - from: "19:05:00"
        to: "23:50:00"
  infra:
    broker:
      trading-account-name: trading_account
    notification.telegram:
      enabled: true
      token: ${TELEGRAM_TOKEN:tgToken}
      chat-id: ${TELEGRAM_CHAT_ID:tgChatId}
      api-url: https://api.telegram.org/bot${application.infra.notification.telegram.token}
  schedule:
    enabled: true
    candle-subscription-refresh-delay: PT15S